version: '3.8'

services:
  # Contenedor PHP
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php-app
    volumes:
      - ./:/var/www/html  # Montamos el código PHP
    # Forward del puerto de Xdebug (si no te funciona host.docker.internal)
    environment:
       XDEBUG_CONFIG: "client_host=host.docker.internal"
       XDEBUG_MODE: "debug"
       XDEBUG_START_WITH_REQUEST: "yes"

  # Contenedor Nginx
  nginx:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php

  # (Opcional) Contenedor MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
